Repository AY2425S2-CS2103-F09-1/tp, pull requests merged in 2025-03, with the labels that each got.

#8 Edit kararei AboutUs.md
  docs/AboutUs.md
  docs/team/johndoe.md
  docs/team/kararei.md
Labels: type.Task

#12 Edit Adwin's AboutUs.md
  docs/AboutUs.md
  docs/team/angYongXiangAdwin.md
Labels: type.Task

#26 Edit zyonwee AboutUs.md
  docs/AboutUs.md
  docs/team/zyonwee.md
Labels: type.Task

#25 Edit Dexter's AboutUs.md
  docs/AboutUs.md
  docs/team/dexterleng.md
Labels: type.Task

#32 Update Ui.png
  docs/images/Ui.png
Labels: type.Task

#46 Update remaining README content page
  README.md
Labels: type.Task

#52 Update Help URL
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#71 Update .gitignore: Add rules to ignore all files in the bin directory
  .gitignore
Labels: type.Task

#79 #78 fix trips disk
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/util/DataLoadingUtil.java
  src/test/java/seedu/address/model/util/DataLoadingUtilTest.java
Labels: type.Bug

#80 Add DeleteTrip feature with tests and utilities
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTripCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTripCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTripCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTripCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement

#81 #76 add notes when add trip
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTripCommand.java
  src/main/java/seedu/address/logic/parser/AddTripCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/trip/Note.java
  src/main/java/seedu/address/model/trip/Trip.java
  src/main/java/seedu/address/storage/JsonAdaptedTrip.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTripCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/trip/NoteTest.java
  src/test/java/seedu/address/model/trip/TripTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTripTest.java
  src/test/java/seedu/address/storage/JsonSerializableTripBookTest.java
  src/test/java/seedu/address/testutil/TripBuilder.java
  src/test/java/seedu/address/testutil/TypicalTrips.java
Labels: type.Story
